export default {
  back: "Back",
  pinyin: "Pinyin",
  explain: "explanation",
  shengmu: " initial consonant",
  danyun: "simple vowel",
  fuyun: "compound vowel",
  zhengti: "whole syllables",
  say: "explanation",
  ok: "OK",
  bushou: "radical",
  cizu: "phrases",
  jiegou: "structure",
  ciyi: "word meaning",
  jinyi: "synonym",
  fanyi: " antonym",
  juzi: "linked sentences",
  allWriteExplain: "You have finished all the exercises correctly.",
  listenExplain:
    "You have listened to all the explanation in ‘Listening’ section.",
  sayExplain:
    "You have scored over 90 in 4-tone learning in ‘Speaking’ section.",
  studyExplain: "You have learned 4 linked words in ‘Learning’ section.",
  writeExplain:
    "You have done a good job in writing pinyin in ‘Writing’ section.",
  listen: "listen",
  speak: "speak",
  study: "study",
  write: "write",
  test: "Test",
  record: "Record",
  finish: "Finish",
  exerciseRocord: "Record",
  yunmu: "vowel",
  guize: "rule",
  allWriteExplainKid: "You have finished all 4 sections.",
};
