let zoom_num = 1
export let sizeObj = {
    "a": { width: 262 * zoom_num, height: 650 * zoom_num },
    "b": { width: 236 * zoom_num, height: 650 * zoom_num },
    "c": { width: 200 * zoom_num, height: 650 * zoom_num },
    "d": { width: 228 * zoom_num, height: 650 * zoom_num },
    "e": { width: 214 * zoom_num, height: 650 * zoom_num },
    "f": { width: 202 * zoom_num, height: 650 * zoom_num },
    "g": { width: 242 * zoom_num, height: 650 * zoom_num },
    "h": { width: 211 * zoom_num, height: 650 * zoom_num },
    "i": { width: 96 * zoom_num, height: 650 * zoom_num },
    "j": { width: 186 * zoom_num, height: 650 * zoom_num },
    "k": { width: 196 * zoom_num, height: 650 * zoom_num },
    "l": { width: 85 * zoom_num, height: 650 * zoom_num },
    "m": { width: 234 * zoom_num, height: 650 * zoom_num },
    "n": { width: 197 * zoom_num, height: 650 * zoom_num },
    "o": { width: 210 * zoom_num, height: 650 * zoom_num },
    "p": { width: 222 * zoom_num, height: 650 * zoom_num },
    "q": { width: 222 * zoom_num, height: 650 * zoom_num },
    "r": { width: 192 * zoom_num, height: 650 * zoom_num },
    "s": { width: 171 * zoom_num, height: 650 * zoom_num },
    "t": { width: 183 * zoom_num, height: 650 * zoom_num },
    "u": { width: 188 * zoom_num, height: 650 * zoom_num },
    "v": { width: 188 * zoom_num, height: 650 * zoom_num },
    "ü": { width: 188 * zoom_num, height: 650 * zoom_num }, // 与v
    "w": { width: 282 * zoom_num, height: 650 * zoom_num },
    "x": { width: 205 * zoom_num, height: 650 * zoom_num },
    "y": { width: 275 * zoom_num, height: 650 * zoom_num },
    "z": { width: 195 * zoom_num, height: 650 * zoom_num },
}