
export const SET_USER = 'SET_USER' //保存基础信息
export const GET_USER = 'GET_USER' //获取基础信息
export const SET_LOCK_PRIMARY_SCHOOL = 'SET_LOCK_PRIMARY_SCHOOL'
export const SET_LOCK_SPECIAL_PRIMARY_SCHOOL = 'SET_LOCK_SPECIAL_PRIMARY_SCHOOL'
export const SET_LOCK_YOUNG = 'SET_LOCK_YOUNG'
export const SET_PURCHASEMODULE = 'SET_PURCHASEMODULE'
export const SET_SELECTMODULE = 'SET_SELECTMODULE'
export const SET_SELECTMODULEAUTHORITY = 'SET_SELECTMODULEAUTHORITY'
