export default {
        "Listen and select the correct letter!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Ti4G9vvFnpSzdudrK6pZr8.wav",
        "Select the correct pronunciation!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Sv3rS5ArjwMzcsypDifPdm.wav",
        "Is this letter big or small?!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/WHwZQ6Mq2BeKj24J9LSwmT.wav",
        "Is this letter big or small?": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/SsS9RdgUhW6mzgs7hSLS7j.wav",
        "What is the missing letter?!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/narDSQWutkxGkoqtajqvVd.wav",
        "What is the missing letter?": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/narDSQWutkxGkoqtajqvVd.wav",
        // "What is the missing letter! ": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/3u5XgmPJvScsEGhKAFWKH6.wav",
        "Please complete the word!  ": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/SUufLgXEYFWrGzee2J9FX6.wav",
        "Listen and repeat!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9nvWRbfwsquQkW5PoeF5JR.wav",
        "Copy and write the letter!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/eBBewP7AFaNwfsJETwkPaa.wav",
        "Write the small letter!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/PEcouEHcoWEyqaBWAUFvdb.wav",
        "Listen and select the correct first letter!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/fHLuYN9KSn8jrpdyg2C8ZT.wav",
        "Listen and select the correct pronunciation!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/PGWLnWJ76nWQU5DMzcPoQp.wav",
        "Complete the word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/QcrpHJ5NKKtkMEcSyjTdQ9.wav",
        "Listen and complete the word.": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/hf3KLAiPSyE4EYVQsyhQij.wav",
        "Write the big letter!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/gDjXNP9Mzezxp3GfRq3jjh.wav",
        "Listen and select the correct word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LGwbgnaKGH5cPnVrhMPHFk.wav",
        "Select the correct sentence!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/NwNY3VTurJY4B4Bbov5ahs.wav",
        "Select the correct phrase!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/JEk4728TDHHJtNnbPKzfYf.wav",
        "Complete the phrase!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/knEqpWyiB2cZJkssX72AQL.wav",
        "Select the correct word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/QDyfAwQqBXiySEfLk3sc8V.wav",
        "Write and complete the word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/eWDhCPLWTt7dHWHLVgxrAR.wav",
        "Choose the correct word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/njHbhCoVz44BiZaLN3ZmVh.wav",
        "Complete the word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/J9mNR7NoY9UjsqyJZHxVBD.wav",
        "Please write the word！": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/JZVp4ogCPbTmbaenjCt5gz.wav",
        "Write and complete the word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/AEBdzTmXfTAMk4FUJc3Kyi.wav",
        "Please complete the word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/j8bwhdM8kcwcvmGxAFDcAK.wav",
        "Listen and complete the word!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/BAkqjJRJCZ3ZR7V5QjSddJ.wav",
        "Look at the picture, what is the correct sentence?": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/m9BxHHR6qsuencxwtQEn2s.wav",
        "Listen and select the correct sentence!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/EQnQzcVURMahrUcfMRj2Bb.wav",
        "Look at the picture and complete the sentence!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LyNoV2jYDxftBqvdm4obzM.wav",
        "Listen and select the word to complete the sentence!": "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/3AjsHk6E4jt8kJcoac3Bio.wav",
        'How many words starting with "A" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/JyrM5TtFPKcgGsKawUsGKF.wav",
        'How many words starting with "B" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/NDpSWGaUFR5fiUMVDzRc7w.wav",
        'How many words starting with "C" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Bc4R5L9vYLYNzUWccJmKFH.wav",
        'How many words starting with "D" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/dKXYPUNvNd5tFjKDnrMhQ5.wav",
        'How many words starting with "E" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/hMNmAvVwVLU7t7uRLLVSqa.wav",
        'How many words starting with "F" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LEFyFv4zxuRYQZSsg6jGBU.wav",
        'How many words starting with "G" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/khsBTjSCBuVjopxExz2FPz.wav",
        'How many words starting with "H" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/hyE7wzxcZ5LArJ6C5SLxGy.wav",
        'How many words starting with "I" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/GmfRNqyUk3NWWUeKJpfUTx.wav",
        'How many words starting with "J" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/aTc6jW8MxNZktCjxQcdFiG.wav",
        'How many words starting with "K" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/oX6rTGwXNp9bXsaqHmW9md.wav",
        'How many words starting with "L" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/ESUgW6AVQCKwGAZcWdvuh5.wav",
        'How many words starting with "M" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/26qJDvMbsNgjyXp9p5xvLP.wav",
        'How many words starting with "N" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9QKjV42K9j6SUn6u5tC2Dh.wav",
        'How many words starting with "O" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/aw4TKTZpe2qsskkUygLFvz.wav",
        'How many words starting with "P" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Xwc2BnxgGVctFaHuet8mfE.wav",
        'How many words starting with "Q" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/jckiUwybwEyFGdH575S68p.wav",
        'How many words starting with "R" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/VavAKqwzmXZK7cYzdVAbyp.wav",
        'How many words starting with "S" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LAsd5txFakQASC7m2kL7My.wav",
        'How many words starting with "T" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/k6rD8gxkJAXMnJjo38z2Eb.wav",
        'How many words starting with "U" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/afKnaJ56ayFQSqYL92Dnqf.wav",
        'How many words starting with "V" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/gizSW5tyAUr3o65fYnh6fc.wav",
        'How many words starting with "W" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/V57oU6fgBbWDKTAgVBcjkh.wav",
        'How many words starting with "X" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/idmzx6pvGZBbjr5N4c9Wdc.wav",
        'How many words starting with "Y" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/KeLQhb5mHLuRhgDduodw3q.wav",
        'How many words starting with "Z" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/hvyWYxq9C99FGENhii5jaj.wav",
        'How many words starting with "a" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/cPFeeArW8a7wsBRuYaMkT4.wav",
        'How many words starting with "b" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/mctCdMp7qK7XZrLRcgpt2R.wav",
        'How many words starting with "c" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/e5NBKnZrWUmrVtv2TedrqA.wav",
        'How many words starting with "d" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/T4dCnyEGU3SPigQrke6Lfk.wav",
        'How many words starting with "e" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/GSWvBnzBQ7W5QCatMAG3Br.wav",
        'How many words starting with "f" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/AvC8PNJhYCuaFZoqCQYrN9.wav",
        'How many words starting with "g" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/aM66nsaJKZTjKbFs265DQb.wav",
        'How many words starting with "h" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/B8sj35kNvrwummzoRepv3E.wav",
        'How many words starting with "i" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Cdor2qPnq6NTBfXYzA2enN.wav",
        'How many words starting with "j" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/FubQkT7BqqYEAhdxhwSqqJ.wav",
        'How many words starting with "k" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/SMDSPUhYFEgQLPWbCHbVfn.wav",
        'How many words starting with "l" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/3qNXfGgK53gn8KNE5KsVUD.wav",
        'How many words starting with "m" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/QisYwk3LeuV2YibG9jVXn3.wav",
        'How many words starting with "n" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/HXiqkFhNikNjx7CP7yd6fX.wav",
        'How many words starting with "o" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/UrJx4jLiFNC8JvYNA34KYi.wav",
        'How many words starting with "p" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/29ioUpfTMeSURs3wqQUF8X.wav",
        'How many words starting with "q" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/K9T6iPSNPiPxi22FtFxe4L.wav",
        'How many words starting with "r" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/KdsFxNgDywducMf3CSYB47.wav",
        'How many words starting with "s" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/BdHbod8Lgsh7ume3A5YuLY.wav",
        'How many words starting with "t" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/QfhQcUmDv6hLJyBJQbabYF.wav",
        'How many words starting with "u" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9vo9pFJHB44MBcvYzKBSQ7.wav",
        'How many words starting with "v" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/3GW7ScvqhJ7ahgpUxLicW9.wav",
        'How many words starting with "w" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/YaGA25npRTZYAhFMAMidy5.wav",
        'How many words starting with "x" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/2DSb28uQhycBtNCmRsJ4qc.wav",
        'How many words starting with "y" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LXvBsDvyYs45UKbRxyZ9n6.wav",
        'How many words starting with "z" did you hear?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9i3XJesrRnxemMCxadMTDx.wav",
        'How many "A"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/o5F9LrUx4fMCgzUv9j4r53.wav",
        'How many "B"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9VX2fqmpWQWQQ5pCXSeiwi.wav",
        'How many "C"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/EL5mmxvjT3s4yYNb2DdQZn.wav",
        'How many "D"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/3zHHwVLNYrTrGhYUFsGkee.wav",
        'How many "E"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Be8b3jXKBkJvFwW5aERsuZ.wav",
        'How many "F"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/6QqiFJVZPfrpcX5HovXZTa.wav",
        'How many "G"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/JHrB6z4knCVqtX7mm4yWme.wav",
        'How many "H"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/oATueQXKfUKQSSGaA2Hie8.wav",
        'How many "I"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/5XfATcbUzBVKGskFHJ2ZaD.wav",
        'How many "J"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/ANSxTWCCAqykd3gPyRFHSM.wav",
        'How many "K"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/gWvFvgLchFPGbJ3WNDfYTP.wav",
        'How many "L"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/HKpyJ5X6UWmuR3rWkfGYTL.wav",
        'How many "M"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/NnrhJdWa9dwS8WAx4nAsaq.wav",
        'How many "N"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kY2nEooQWEdWYssiQ2dMWw.wav",
        'How many "O"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/SDcEUd5ZSEagtBbZWMCvsb.wav",
        'How many "P"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/agP6o89yxPGdY6GNKRHk6N.wav",
        'How many "Q"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/2wtsjULR2eqUisDNYFqYVp.wav",
        'How many "R"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/YVr2Pxu9FGdPkJdkTPtC9H.wav",
        'How many "S"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/RHM3LrJy4udyvXVKLPhgNM.wav",
        'How many "T"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/78SfgFCeVMyXaG2pQz7LHS.wav",
        'How many "U"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/98REkWAvy2hDNLqj2FsTzk.wav",
        'How many "V"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/cqo8PERFsFmGEbMhhn6836.wav",
        'How many "W"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Run7wMTmpqk9wCXY9ne6JP.wav",
        'How many "X"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/HZaNLmsJEk62rv6N2u8U9C.wav",
        'How many "Y"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/PP6HGMTGRg72LES99u2dEG.wav",
        'How many "Z"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/HCKpm53qkLT9S2TGAnyzS7.wav",
        'How many "a"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/8UNsSA2nPKdPmNPFLwvV72.wav",
        'How many "b"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/nsjdfUsZLktkgNfWuDZvaA.wav",
        'How many "c"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/XHRZ84r3Ai8LCtNboZBZGB.wav",
        'How many "d"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/HEgJeB6Trd4Dwav3ugPLeE.wav",
        'How many "e"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/SHuDYvi7t9jETzSLck3Y4m.wav",
        'How many "f"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/YJRA8neXGwRCd8uQgJmnrG.wav",
        'How many "g"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kmhHZgKKnZzaMxkSyZneMt.wav",
        'How many "h"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/RgBXikUdBfheF4r7RTGgHk.wav",
        'How many "i"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/DV6iyXsuzRyeRDVZfkgedT.wav",
        'How many "j"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/EXht77FY5RrigbEV4G3oBo.wav",
        'How many "k"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/gSUEBeVEJwnUT7UounQKjJ.wav",
        'How many "l"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/FQSRbbySkChoGnhXhKr3bS.wav",
        'How many "m"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/G8XduwXN3HjucZigLxGrZQ.wav",
        'How many "n"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/6xQAxvxG6tC2ZjT2enyyFg.wav",
        'How many "o"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/h2hWaG27J7XWfbrh22CLxc.wav",
        'How many "p"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kHW79qrGXCeceatq4Ureme.wav",
        'How many "q"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Ynzxb48t2doGUWhENUVMGS.wav",
        'How many "r"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/6MTZBPnCsyu2UTPFsf6v2j.wav",
        'How many "s"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/NesCfCyVKPeDSZ6WyPV9kj.wav",
        'How many "t"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/SmwdPeCjyQeHtsm3VT2iEZ.wav",
        'How many "u"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Fss8MgDHicM2huB5GQHEQw.wav",
        'How many "v"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/2wg3u34F43gXBNbptHtKxL.wav",
        'How many "w"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/MAKQe8SbCRrms5fvy2D4Ns.wav",
        'How many "x"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/agbaDMWTuQpDaHcnT55wFY.wav",
        'How many "y"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9KYY68ujTvWtPFHJic3GJS.wav",
        'How many "z"s are in the word?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/6kiZ46H5nuaXipghGyt4ds.wav",
        'How many "A"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/R9Gh7UA2Nnkncjjn35ijRz.wav",
        'How many "B"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kQin5Ua6SF5KysrxcGBgBF.wav",
        'How many "C"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/JXHoVavogWnEYpJ6Q56q35.wav",
        'How many "D"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/b38cep5do6j5GWSs2zcziZ.wav",
        'How many "E"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/GW3HspHm4XC5itVm4DSzQB.wav",
        'How many "F"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/m3YvabCL6oJvk3qGX4d7s3.wav",
        'How many "G"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/C5BBKgr2cdZxKQrdFvX5Hr.wav",
        'How many "H"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/de24mGocWeD35af9M9ruaA.wav",
        'How many "I"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LktPzm5ffMGQ7ra2xD74Ma.wav",
        'How many "J"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LkmGTafEZUxrWG6H7eCmwX.wav",
        'How many "K"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/QT2eKGCZeU8TbzkHGYNhmc.wav",
        'How many "L"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/TtG7yT3ani4p546ThbSamC.wav",
        'How many "M"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/U55Vshc4Ugxdw9JNWqVd84.wav",
        'How many "N"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/QSstxXNcVa3Toc3sds9w9w.wav",
        'How many "O"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Fw3jtRRuGZmtoQhjqotuvR.wav",
        'How many "P"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/ecCJMkU4DdkQYWcjwv8Xop.wav",
        'How many "Q"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Lwtqm6UUyh7cnyMbgCACjS.wav",
        'How many "R"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/BHXfkWba8nMYwuebt224mU.wav",
        'How many "S"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/FkUHjs9d2CVE57ZNexTDKH.wav",
        'How many "T"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/4NqxzDoKVF5WzkWxok6nTA.wav",
        'How many "U"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/4nH5awWa9N4zBExgpWtY9R.wav",
        'How many "V"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/JbaYtcmkVYpq66khg6p3BP.wav",
        'How many "W"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/2qSGNgYsfEUcoK3BsNoy7L.wav",
        'How many "X"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/4opZZNdtqFfS7yfKdnkMT4.wav",
        'How many "Y"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/GB7XVQH4DxxoDMyQwuNNxS.wav",
        'How many "Z"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/HjmGWrQndsoPuQ393G87zC.wav",
        'How many "a"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/6ywLXn3SvNZxdQzo4xbgLa.wav",
        'How many "b"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kFzehdH9iQE7DPGQ96JtRu.wav",
        'How many "c"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Nxbh6FhJnrNBiqpVAY8k2d.wav",
        'How many "d"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/A6of5pU4YUNiEv9VtqPo9J.wav",
        'How many "e"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/5dXzrWw8q2z28c2Qn2CzH9.wav",
        'How many "f"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/QNxFAsWmC2Kyj3aMRu9rZw.wav",
        'How many "g"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/34kKDHFH6WBA5FRmpyUcw4.wav",
        'How many "h"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/cVm6FDUu59ULxcxF9SdXdd.wav",
        'How many "i"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/nGRvkfgvWivcW9ykmpxH5b.wav",
        'How many "j"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/mNb7ztc3EcMbnojUGgzpWy.wav",
        'How many "k"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kms7AhkmtySaAkscjQ3V5y.wav",
        'How many "l"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/ax5wabzMkbCNJUEczT9Mah.wav",
        'How many "m"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/eYMd9gAFtcfuDsWcVgLCLe.wav",
        'How many "n"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/7gLJNvNKM3myCUT8DXHKHf.wav",
        'How many "o"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/TpDUzM7LjtLzyPYv8drLzF.wav",
        'How many "p"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/hEyJsKLhHPdffXtu6nWJpo.wav",
        'How many "q"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/JA84hL9E6GvZwJ2gvZcKSK.wav",
        'How many "r"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/ShrGvVTkZYnqgy3iKDHBYY.wav",
        'How many "s"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kCGdK8AH7L8mvnCfELo9ZD.wav",
        'How many "t"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/gLZnt4DRrqbQt7iYnQeN2n.wav",
        'How many "u"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/W6Mnd5nYZdb9pjqgEcgaTd.wav",
        'How many "v"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/f6o9zHPJQNAkFSt2XUCg22.wav",
        'How many "w"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/kXVNiHrptfjfh6qefUrC3H.wav",
        'How many "x"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/dAhWLZosgtaUhWRxPzSYor.wav",
        'How many "y"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/7AMMnoFtX9eUPzfVh4E2Q6.wav",
        'How many "z"s can you find?': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/PsGG6vMvZtdWGVnX7zWgLL.wav",
        'Select the words starting with "A"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/jh5dpAtPt7AqdWFCsv3cH4.wav",
        'Select the words starting with "B"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Wwzji5r3qeS9zW9rGH78AM.wav",
        'Select the words starting with "C"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9sr2KGraYtxmn4QCw6UdiN.wav",
        'Select the words starting with "D"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/FtoaWepm9yRJ2B5brAGmZ3.wav",
        'Select the words starting with "E"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/c3w5gDJBJxn9T4oPWHvqN2.wav",
        'Select the words starting with "F"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/dXcZHUaFthyWjgM6yQimCS.wav",
        'Select the words starting with "G"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/WwvYtW4vEgcrhSaCprS2fX.wav",
        'Select the words starting with "H"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/SCESQ32Q2VfM3MU2oxHdpY.wav",
        'Select the words starting with "I"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/HGehThcz9bdvmq5y3UkZFv.wav",
        'Select the words starting with "J"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/TkbnWuatyj5ysidasfpijD.wav",
        'Select the words starting with "K"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/2rgmxxYpaUE7KC2BzwZptX.wav",
        'Select the words starting with "L"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/bwkFTm4ZFxqYMMbPqyDoMv.wav",
        'Select the words starting with "M"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/DMtuRAxp4CdvryRskoxtxX.wav",
        'Select the words starting with "N"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/MnqF3QNaRYYZBFocXTWiqZ.wav",
        'Select the words starting with "O"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/oPWhAnuqE4NXJKAhPf6KoK.wav",
        'Select the words starting with "P"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/LH5sQRRLzuKEXwtLcprsky.wav",
        'Select the words starting with "Q"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/ZawLbt3zbGjph6hnHJMf5C.wav",
        'Select the words starting with "R"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/8zY62a3nPKZosaAZCqvMmi.wav",
        'Select the words starting with "S"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Gk9aujV8XQdG4B7FvBChXE.wav",
        'Select the words starting with "T"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/c5YxwepukBDyDYGRVMvD3o.wav",
        'Select the words starting with "U"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/f29rxpPDZdLaKhaNgtNgQa.wav",
        'Select the words starting with "V"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/EMFLfds2pAEk94DYdAwBBq.wav",
        'Select the words starting with "W"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/CwX4bAj9FUddarW9JCzQdT.wav",
        'Select the words starting with "X"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/YDoBrrm3yA6VuAyFNqceoz.wav",
        'Select the words starting with "Y"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/2QmiQ7S8T2NBDizpFL7cTV.wav",
        'Select the words starting with "Z"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/EQcT8Pqvj4CnEpcyoR6j73.wav",
        'Select the words starting with "a"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/9edUQmspxFhMxwKdyvWamf.wav",
        'Select the words starting with "b"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/CjHmTbaep2U3ZPeYwCyUpM.wav",
        'Select the words starting with "c"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/nsnWqtEWB3GvsruU6GEukm.wav",
        'Select the words starting with "d"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Vz9PCoZgRazxrvifR9YFXv.wav",
        'Select the words starting with "e"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/5GodFLGiCo6oWQCCLYReZN.wav",
        'Select the words starting with "f"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/VrY74eoKdNTC9RMvZ5PVCx.wav",
        'Select the words starting with "g"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Votuc74xVLPNN3cpmDNdbi.wav",
        'Select the words starting with "h"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Bki8tV5jHkAUtnLAJn7MRq.wav",
        'Select the words starting with "i"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/6qxrBBtjJyLs8LZVwz6kcA.wav",
        'Select the words starting with "j"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/S4QpvJ8KTNJcQshQfEpDxq.wav",
        'Select the words starting with "k"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/jGaeAffxK4EKLJSB5UNwXg.wav",
        'Select the words starting with "l"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/2haCu7DmkUwnFzoKry5GJR.wav",
        'Select the words starting with "m"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/i7JjnFrJUmxh6329pidzph.wav",
        'Select the words starting with "n"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/eNzsEDa9ZC7QhvjryZJvoV.wav",
        'Select the words starting with "o"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/bPhQA8UGcaR3LB6dUVGCMa.wav",
        'Select the words starting with "p"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/Nitoek2ZVaxUAKwNtri5DR.wav",
        'Select the words starting with "q"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/bKs85f9Hp2o2JQF2mev58e.wav",
        'Select the words starting with "r"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/R3ty6szKwHXiyaTsopHLNP.wav",
        'Select the words starting with "s"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/mah6N9Mf9cwrzAbGaE3gsy.wav",
        'Select the words starting with "t"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/7ZX8JcrtGWS9s93kKkbHYz.wav",
        'Select the words starting with "u"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/B3ETHtKJnGZG3EJtRpPRpR.wav",
        'Select the words starting with "v"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/XusqbvN87dLvTXKAo5DWbo.wav",
        'Select the words starting with "w"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/PGFjnr2xpfDSFxShz4U63c.wav",
        'Select the words starting with "x"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/oYR9EVPRbuwmAgCrkgeX3g.wav",
        'Select the words starting with "y"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/N4xLiHUQPLMygjLr57QTX8.wav",
        'Select the words starting with "z"!': "https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/eXZyVYT4rYj6pdjtjEY2ax.wav",
        'Listen and select the first letter!':'https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/5m9s8Q3JpY78P2ky9mRg6E.wav',
        'What is the first letter?':'https://pailaimi-static.oss-cn-chengdu.aliyuncs.com/audio/paixiaoxue/stem/82CdAz2bZJofxWungYPaWM.wav'

}