export default {
    'back': 'Back',
    'shijianxian': 'Progress',
    'zsdjiangjie': 'Explanation',
    'practice': 'Practice',
    'zstupu': 'Infographics',
    'badge_des_1': 'Gold badge: all correct!',
    'badge_des_2': 'Silver badge: nearly there!',
    'badge_des_3': 'Knowledge points that have not yet answered the exercise questions.',
    'wodehzhgz': 'My badges',
    'draft': 'Draft',
    '0100': 'Grade 1 1st Term',
    '0101': 'Grade 1 2nd Term',
    '0200': 'Grade 2 1st Term',
    '0201': 'Grade 2 2nd Term',
    '0300': 'Grade 3 1st Term',
    '0301': 'Grade 3 2nd Term',
    '0400': 'Grade 4 1st Term',
    '0401': 'Grade 4 2nd Term',
    '0500': 'Grade 5 1st Term',
    '0501': 'Grade 5 2nd Term',
    '0600': 'Grade 6 1st Term',
    '0601': 'Grade 6 2nd Term',
    'submit': 'Submit',
    'correct_answer': 'Correct answer',
    'jiexi': 'Analysis',
    'next': 'Next',
    'jietisl': 'How to solve the problem',
    'ok': 'Ok',
    'fenshu': 'Fractions',
    'daifenshu': 'Mixed Fractions',
    'noselectanswer': "You didn't choose the answer",
    'excellent': "Excellent",
    'allcompleted': 'All completed',
    'correct': 'Right',
    'error': 'Wrong',
    'exit': 'Exit',
    '判断题': 'True or false?',
    '填空题': 'Fill in the blanks!',
    '选择题': 'Choose the correct answer!',
    '计算题': "Let's calculate!",
    '应用题': "Let's solve it!",
    '比较大小': "Bigger or smaller?",
    'program': 'Program',
    'Free':'Free',
    'tip1':'you are great!',
    'tip2':'The accuracy rate is not good, go and improve it!',
    'tip3':'You are great, go take the AI improvement challenge!',
    'tryAgain':'Try again',
    'haode':'Ok',
    'expand':'expand'
}
